fps: 20
calib:
  if_recalib: false
  calib_seconds: 600
  lane_width: 3.75
  emgc_width: 3.5
  cell_len: 50
  q_merge: 0
prepro:
  max_complete_frames: 20
  smooth_alpha: 0.1
traffic:
  q_duration: 300
  cal_interval: 30
event:
  event_types: ["spill","stop", "low_speed", "high_speed", "emergency_break", "incident", "crowd", "illegal_occupation"]
  t_tolerance: 300
  q_standard: 10000
  rate2: 0.1
  v_static: 1
  duration_static: 5
  v_low: 2.778
  duration_low: 5
  v_high: 33.33
  duration_high: 5
  a_intense: 3
  duration_intense: 1
  d_touch: 5
  t_supervise: 20
  density_crowd: 18
  v_crowd: 16.667
  duration_occupation: 5
