ip: 'loacalhost:9092'
topic: 'trafficTrajectory'
group: 'group'
key: None
http: 'http://localhost:5000'

fps: 20

ifRecalib: false
calibSeconds: 600
laneWidth: 3.75
emgcWidth: 3.5
cellLen: 50
qMerge: 0

maxCompleteTime: 2
smoothAlpha: 0.1

qDuration: 300
calInterval: 30

eventTypes: ["spill", "stop", "lowSpeed", "highSpeed", "emgcBrake", "incident", "crowd", "illegalOccupation"]
tTolerance: 300
qStandard: 10000
vLateral: 0.56
rate2: 0.0017
spillWarnFreq: 300
vStop: 1
durationStop: 3
vLow: 2.778
durationLow: 3
vHigh: 33.33
durationHigh: 3
aEmgcBrake: 3
durationEmgcBrake: 1
dTouch: 5
tSupervise: 20
densityCrowd: 18
vCrowd: 5.555
durationOccupation: 3
