ip: '192.168.1.31:9092'
topic: 'trafficTrajectory'
groupid: None
producerversion: [2, 8, 1]
key: None
http: 'http://192.168.1.31:20490'
# donglan test
# ip: '192.168.1.31:9092'
# topic: 'trafficTrajectory'
# groupid: None
# producerversion: [2, 8, 1]
# key: None
# http: 'http://192.168.1.31:20490'
# local test
# ip: 'localhost:9092'
# topic: 'test'
# groupid: None
# producerversion: [2, 8, 1]
# key: None
# http: 'http://localhost:20490'

kafkaAutoCommitIntervalMs: 5000
fps: 20

ifRecalib: false
calibSeconds: 300
laneWidth: 3.75
emgcWidth: 3.5
cellLen: 50
qMerge: 0

maxCompleteTime: 2
smoothAlpha: 0.1

qDuration: 300
calInterval: 30

eventTypes: ["spill", "stop", "lowSpeed", "highSpeed", "emgcBrake", "incident", "crowd", "illegalOccupation"]
tTolerance: 300
qStandard: 10000
vLateral: 3
rate2: 0.0017
spillWarnFreq: 300
vStop: 1
durationStop: 3
vLow: 2.778
durationLow: 3
vHigh: 33.33
durationHigh: 3
aEmgcBrake: 3
durationEmgcBrake: 1
dTouch: 5
tSupervise: 20
densityCrowd: 18
vCrowd: 5.555
durationOccupation: 3
