ip: '10.121.25.234:9092'
topic: 'trafficTrajectory'
groupid: None
producerversion: [2, 8, 1]
key: None
http: 'http://10.121.25.234:19025'
deviceIDs: ["K68+366", "K68+400", "K69+000", "K69+800", "K71+616", "K73+516", "K75+001", "K76+781", "K78+760", "K79+886", "K80+850", "K80+880", "K81+320", "K81+866"]
deviceTypes: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
# donglan test
# ip: '192.168.1.31:9092'
# topic: 'trafficTrajectory'
# groupid: None
# producerversion: [2, 8, 1]
# key: None
# http: 'http://192.168.1.31:20490'
# local test
# ip: 'localhost:9092'
# topic: 'test'
# groupid: None
# producerversion: [2, 8, 1]
# key: None
# http: 'http://localhost:20490'

kafkaAutoCommitIntervalMs: 5000
fps: 20

ifRecalib: false
calibSeconds: 600
laneWidth: 3.75
emgcWidth: 3.5
cellLen: 50
qMerge: 20

maxCompleteTime: 2
smoothAlpha: 0.1

qDuration: 300
calInterval: 30

# eventTypes: ["spill", "stop", "lowSpeed", "highSpeed", "emgcBrake", "incident", "crowd", "illegalOccupation"]
eventTypes: ["spill", "stop", "incident", "crowd", "illegalOccupation"]
tTolerance: 300
qStandard: 10000
vLateral: 3
rate2: 0.0005
WarnFreq: 300
vStop: 2.22
durationStop: 1
vLow: 11.11
durationLowSpeed: 3
vHigh: 33.33
durationHighSpeed: 3
aEmgcBrake: 3
durationEmgcBrake: 1
dTouch: 3
tSupervise: 20
densityCrowd: 18
vCrowd: 5.555
durationIllegalOccupation: 5
cacheSeconds: 60
