fps: 20

ifRecalib: false
calibSeconds: 600
laneWidth: 3.75
emgcWidth: 3.5
cellLen: 50
qMerge: 0

maxCompleteFrames: 20
smoothAlpha: 0.1

qDuration: 300
calInterval: 30

eventTypes: ["spill", "stop", "lowSpeed", "highSpeed", "emgcBrake", "incident", "crowd", "illegalOccupation"]
tTolerance: 300
qStandard: 10000
vLateral: 0.56
rate2: 0.1
spillWarnFreq: 300
vStop: 1
durationStop: 5
vLow: 2.778
durationLow: 5
vHigh: 22.22
durationHigh: 5
aEmgcBrake: 3
durationEmgcBrake: 1
dTouch: 5
tSupervise: 20
densityCrowd: 18
vCrowd: 16.667
durationOccupation: 5
